# Generated by Django 5.2 on 2025-04-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zonas_geograficas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_o_provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('coordenadas', models.CharField(max_length=100)),
                ('nivel_de_conectividad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zonas_geograficas',
            },
        ),
        migrations.CreateModel(
            name='Direction_ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_ip', models.IntegerField()),
                ('asn', models.CharField(max_length=100)),
                ('provedor', models.CharField(max_length=100)),
                ('id_zona_georafica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubip.zonas_geograficas')),
            ],
            options={
                'db_table': 'direction_ip',
            },
        ),
    ]
